version: '3.8'

services:
  smart-home-backend:
    build: .
    container_name: smart-home-backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/mydatabase
      PORT: 3000
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 

  mongo:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - '9000:9000'
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonarqube-db

  sonarqube-db:
    image: postgres:12
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  sonarqube-db-data:
